### ISSUE TITLE
Private forks of public repos are not allowed by Github

### ISSUE THREAD

**Issue by GWFrank** [cwlin1998/reversi-pygame#31]
Github currently hasn't allowed private forks of public repositories, should we [duplicate the repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) as it suggests or use the [import a repository feature](https://github.com/new/import)?

**Comment by MarvinChung** [comment]
An organization owner must allow forks of private repositories on the organization level before you can allow or disallow forks for a specific repository. see “[Allowing people to fork private repositories in your organization](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-the-forking-policy-for-your-organization)". However we should pay money for team features.
It seems like [duplicate the repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/duplicating-a-repository) is a good method. 
Let's move on it and change the README.md.

**Comment by MarvinChung** [comment]
Thanks for reporting the issue!

**Comment by MarvinChung** [comment]
By the way, you earn two bonus points for your team.
