### ISSUE TITLE
About 'obs' parameter in step function of BaseAgent

### ISSUE THREAD

**Issue by ChenKB91** [cwlin1998/reversi-pygame#35]
```py
    def step(self, reward, obs):
        """
        Parameters
        ----------
        
...            
        obs    :  dict 
            board status

            key: int 0 ~ 63
            value: [-1, 0 ,1]
                    -1 : black
                     0 : empty
                     1 : white
        """
```
Does the key work like this
| 0    | 1    | 2    | ...7  |
| ---- | ---- | ---- | ----- |
| 8    | 9    | 10   | ...15 |
| 16   | 17   | 18   | ...   |

or its transpose? ~(too lazy to type it again lol)~

**Comment by MarvinChung** [comment]
Yes, the key works like your table. 
![image](https://user-images.githubusercontent.com/22186310/100223732-d6a89f00-2f56-11eb-897e-4a090f2e2f16.png)

For those who doesn't understand, A1=0, B1=1 and A2=8
