### ISSUE TITLE
About importing from self-made package

### ISSUE THREAD

**Issue by GWFrank** [cwlin1998/reversi-pygame#42]
Say user `foo` submit his files, according to `README.md`, the file structure should look like this:
```
    ├── agent
    │   ├── foo.py
    │   ├── foo
    │   │   ├── __init__.py
    │   │   └── win.py, ....
    │   │
    │   └── base_agent.py 
```

In `foo.py`, it's something like this:
``` python
...
from .foo.win import my_func # relative import
...
```

However, when `arena.py` try to import `foo.MyAgent`, it will look for `MyAgent` in package `foo`(the `foo` folder) instead of `foo.py`, resulting in `AttributeError: module 'agent.foo' has no attribute 'MyAgent' `

Are there any suggested solution under current rules? My temporarily solution to this is to have the `foo` folder with a different name like `foo_func`, which doesn't follow the rules in `README.md`.

**Comment by GWFrank** [comment]
Btw, either using absolute import or removing `__init__.py` didn't help.

**Comment by MarvinChung** [comment]
@cwlin1998 I think we should modify the rules instead of using other ways to pass through the import error.
The rules might be changed as follows:
- Put your agent in agent_folder and name it using your team leader's github id with a suffix.
For example:
    ```
    ├── agent
    │   ├── cwlin1998.py
    │   ├── cwlin1998_func/    # put your other files under this folder
    │   └── base_agent.py 
    ```
