### ISSUE TITLE
Black Screen Problem

### ISSUE THREAD

**Issue by haha246** [cwlin1998/reversi-pygame#49]
![image](https://user-images.githubusercontent.com/71302574/102181974-7322e900-3ee6-11eb-8b22-d6e20c3f24a6.png)

I opened the pygame window by using the code "python arena.py --agent1 moose1108.MyAgent --agent2 base_agent.RandomAgent".
But it broke down as a black screen shown in the picture above.

However, in contrast, when I entered the code "python arena.py --agent1 base_agent.RandomAgent --agent2 moose1108.MyAgent" into my terminal, the program suddenly ran successfully.

![image](https://user-images.githubusercontent.com/71302574/102181772-2c34f380-3ee6-11eb-9e90-325778738f90.png)

![image](https://user-images.githubusercontent.com/71302574/102182650-98642700-3ee7-11eb-8681-3be575d4ae49.png)

I don't know where the problem is, help me plz.

**Comment by MarvinChung** [comment]
You may need to provide more information about it.  
I guess the code above is in your C.T.Lu branch.  
I clone your branch and checkout to C.T.Lu branch.
After typing
```
python arena.py --agent1 moose1108.MyAgent --agent2 base_agent.RandomAgent
```
It works fine in my MAC computer. 
Does it work fine in your teammates' computer?

**Comment by haha246** [comment]
After testing, it worked fine.
It seems that there are some problems on my computer, which caused the black screen.

Anyway, the problem has been solved.  Thank you very much!
